# Generated by Django 5.2.7 on 2025-10-24 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='name_initial',
            field=models.CharField(blank=True, db_index=True, max_length=10, verbose_name='名称首字母'),
        ),
    ]
